spring.application.name=sensor-registry
server.port=1291
spring.datasource.url=jdbc:mysql://localhost:3306/aquapulse
spring.datasource.username=root
spring.datasource.password=Vivek2000
spring.jpa.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.format_sql=true